name: easypost
description: A Dart SDK for EasyPost to interact with the API, plus helper methods.
version: VERSIONADDEDBYGITHUB
repository: https://github.com/nwithan8/easypost-dart

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  http: ^1.1.2
  http_parser: ^4.0.0
  json_annotation: ^4.8.1
  meta: ^1.3.0
  reflectable: ^4.0.5
  tuple: ^2.0.1
  intl: ^0.19.0
  crypto: ^3.0.3

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  collection: ^1.15.0
  dependency_validator:
  lints: ^3.0.0
  mockito: ^5.0.0
  pub_semver:
  test: ^1.16.0
  yaml: ^3.0.0
  yaml_edit:
  dartvcr: ^0.3.0
  json_serializable: ^6.7.0

targets:
  builders:
    reflectable:
      generate_for:
        - src/api/parameters/_base.dart
      options:
        formatted: true
